language: php

php:
  - '5.6'
  - '7.0'
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

install: composer install --no-interaction --prefer-source

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml

after_success:
    - travis_retry php vendor/bin/coveralls
